// This file is autogenerated by Redwood and will be overwritten periodically

import { RedwoodRecord } from '@redwoodjs/record'

import { db } from 'src/lib/db'
import datamodel from 'src/models/datamodel'
import Embedding from 'src/models/Embedding'
import FileUpload from 'src/models/FileUpload'
import OpenAIInteraction from 'src/models/OpenAIInteraction'
import Thread from 'src/models/Thread'

RedwoodRecord.db = db
RedwoodRecord.schema = datamodel

Embedding.requiredModels = []
FileUpload.requiredModels = []
OpenAIInteraction.requiredModels = []
Thread.requiredModels = []

export { Embedding, FileUpload, OpenAIInteraction, Thread }
